"""Export the database schema, and a sanitized data-only dump.

The schema file is safe to commit. The data dump keeps every table the app
needs to boot, but scrubs credentials and drops the bulky log/media tables:

    python scripts/db_export.py            # schema + sanitized data
    python scripts/db_export.py schema     # scripts/schema.sql only
    python scripts/db_export.py data       # backup/data-<date>.sql only

Runs on the host, not inside the app container, and shells out to pg_dump in
the Postgres container so the DB password never has to leave it.
"""

from __future__ import annotations

import argparse
import hashlib
import shlex
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterable, Iterator

CONTAINER = "safefamily_db"
REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO_ROOT / "scripts" / "schema.sql"
BACKUP_DIR = REPO_ROOT / "backup"
# Postgres runs everything here once, when the db_data volume is first
# initialized. Gitignored, so it is per-host and has to be kept in step by hand
# - which is what refresh_init_dump does.
INIT_DB_PATH = REPO_ROOT / "deploy" / "init_db" / "dump.sql"
INIT_MARKER = "-- Generated by scripts/db_export.py"
INIT_HEADER = f"""--
-- SafeFamily first-boot schema for docker-compose.
--
{INIT_MARKER} from the live database, as a copy of
-- scripts/schema.sql. Do not edit by hand - rerun:
--     python scripts/db_export.py schema
--
-- Schema only: no rows, no credentials, safe on any host. Seed rows
-- (audit_item) are not here; they come from scripts/migrate.py, which is a
-- clean no-op against this schema apart from those inserts:
--     docker exec safefamily_app python scripts/migrate.py
--

"""

# Dumped as empty tables: the schema is kept so a restore still works, but the
# rows are left out because they are huge (logs), binary (media), or worthless
# after a restore (short-lived auth artifacts).
EXCLUDE_DATA = [
    "logs",
    "logs_daily",
    "suspicious",
    "media",
    "token_blocklist",
    "auth_codes",
]

# Columns rewritten on the way out, as {table: {column: rule}}. users rows are
# kept (scrubbed) rather than dropped, because todo_list, long_term_goals,
# long_term_goals_his and user_rule_assignment carry FKs onto users.id, and a
# restore would fail at ADD CONSTRAINT if the parent rows were missing.
SCRUB = {
    "public.users": {"password_hash": "redact", "email": "blur_email"},
}

# COPY's text format spells NULL this way; those cells are left alone.
NULL = r"\N"


def blur_email(value: str) -> str:
    """Keep the first character, hash the rest: 'z***a1b2c3@example.invalid'.

    Deterministic, so re-running produces a stable diff, and distinct per input,
    which matters because users.email carries a UNIQUE constraint.
    """
    digest = hashlib.sha256(value.encode()).hexdigest()[:6]
    return f"{value[0]}***{digest}@example.invalid"


RULES = {
    "redact": lambda _value: "!",
    "blur_email": blur_email,
}


def pg_dump(extra_args: list[str]) -> Iterator[str]:
    """Stream pg_dump from the Postgres container, yielding its output lines."""
    inner = 'pg_dump -U "$POSTGRES_USER" "$POSTGRES_DB" ' + " ".join(
        shlex.quote(arg) for arg in extra_args
    )
    with tempfile.TemporaryFile(mode="w+") as errors:
        proc = subprocess.Popen(  # noqa: S603 - fixed argv, no shell on this side
            ["docker", "exec", CONTAINER, "sh", "-c", inner],  # noqa: S607 - docker is on PATH
            stdout=subprocess.PIPE,
            stderr=errors,
            text=True,
        )
        with proc.stdout:
            yield from proc.stdout
        if proc.wait() != 0:
            errors.seek(0)
            message = f"pg_dump failed:\n{errors.read()}"
            raise SystemExit(message)


def copy_header(line: str) -> tuple[str, list[str]] | None:
    """Return (table, columns) if the line opens a COPY block needing a scrub."""
    if not line.startswith("COPY "):
        return None
    table = line.split()[1]
    if table not in SCRUB:
        return None
    names = line[line.index("(") + 1 : line.rindex(")")].split(",")
    columns = [name.strip() for name in names]
    missing = sorted(set(SCRUB[table]) - set(columns))
    if missing:
        message = (
            f"refusing to dump: {table} has no column(s) {missing} - "
            "the scrub rules are stale, fix SCRUB before exporting"
        )
        raise SystemExit(message)
    return table, columns


def scrub_row(line: str, table: str, columns: list[str]) -> str:
    """Apply this table's scrub rules to one tab-separated COPY data row."""
    fields = line.rstrip("\n").split("\t")
    for column, rule in SCRUB[table].items():
        index = columns.index(column)
        if fields[index] != NULL:
            fields[index] = RULES[rule](fields[index])
    return "\t".join(fields) + "\n"


def scrub_lines(lines: Iterable[str]) -> Iterator[str]:
    """Rewrite sensitive columns inside the COPY blocks of a plain-text dump."""
    table: str | None = None
    columns: list[str] = []
    scrubbed: set[str] = set()

    for line in lines:
        if table is None:
            header = copy_header(line)
            if header is not None:
                table, columns = header
            yield line
        elif line.rstrip("\n") == r"\.":
            scrubbed.add(table)
            table = None
            yield line
        else:
            yield scrub_row(line, table, columns)

    expected = {name for name in SCRUB if name.split(".")[-1] not in EXCLUDE_DATA}
    if expected - scrubbed:
        message = (
            f"refusing to dump: expected COPY block(s) {sorted(expected - scrubbed)} "
            "never appeared - the dump layout changed, do not trust this file"
        )
        raise SystemExit(message)


def psql_values(query: str) -> list[str]:
    """Run a one-column query in the container and return its non-empty rows."""
    inner = f'psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -tAc {shlex.quote(query)}'
    result = subprocess.run(  # noqa: S603 - fixed argv, no shell on this side
        ["docker", "exec", CONTAINER, "sh", "-c", inner],  # noqa: S607 - docker is on PATH
        capture_output=True,
        text=True,
        check=True,
    )
    return [line for line in result.stdout.splitlines() if line.strip()]


def verify(path: Path) -> None:
    """Re-read the finished dump and delete it if any live secret survived."""
    text = path.read_text()
    leaks = []
    for table, rules in SCRUB.items():
        for column in rules:
            query = f"SELECT {column} FROM {table} WHERE {column} IS NOT NULL"  # noqa: S608 - names come from SCRUB, not input
            leaks += [
                f"{table}.{column}: {value[:12]}..."
                for value in psql_values(query)
                if value in text
            ]
    if leaks:
        path.unlink()
        message = f"LEAK - deleted {path}\n  " + "\n  ".join(leaks)
        raise SystemExit(message)
    checked = ", ".join(f"{t}.{c}" for t, rules in SCRUB.items() for c in rules)
    print(f"verified: no live values of {checked} appear in {path.name}")


def drop_restrict(lines: Iterable[str]) -> Iterator[str]:
    r"""Strip pg_dump's \restrict / \unrestrict guards.

    Their token is random per run, which would churn the diff of this tracked
    file on every regeneration, and psql below 15.14 rejects the command
    outright (the host's psql 14 does). They guard against psql meta-commands
    smuggled in through dumped *data*, and a schema-only dump carries none - so
    this is dropped here but deliberately kept in the data dump.
    """
    return (line for line in lines if not line.startswith(("\\restrict ", "\\unrestrict ")))


def carries_data(path: Path) -> bool:
    """Say whether a dump has rows in it, reading only as far as the first one."""
    with path.open() as handle:
        return any(line.startswith(("COPY ", "INSERT INTO ")) for line in handle)


def refresh_init_dump(schema: str) -> None:
    """Mirror the schema into deploy/init_db/dump.sql, so first boot stays in step.

    Skipped when the directory is absent (nothing mounts it), or when the file
    already there has rows in it: a full dump is somebody's backup and carries
    live password hashes, so it is never clobbered. A schema-only file is
    replaced whoever wrote it, since it is reproducible from this database.
    """
    if not INIT_DB_PATH.parent.is_dir():
        return
    relative = INIT_DB_PATH.relative_to(REPO_ROOT)
    if INIT_DB_PATH.exists() and carries_data(INIT_DB_PATH):
        print(f"skipped {relative}: it has rows in it, so it is a backup, not an init file")
        print("  move it aside first if you want it replaced")
        return
    INIT_DB_PATH.write_text(INIT_HEADER + schema)
    print(f"refreshed {relative} (docker first-boot init)")


def export_schema() -> None:
    """Write the full DDL (tables, indexes, constraints, sequences) to scripts/."""
    args = ["--schema-only", "--no-owner", "--no-privileges"]
    schema = "".join(drop_restrict(pg_dump(args)))
    SCHEMA_PATH.write_text(schema)
    print(f"wrote {SCHEMA_PATH.relative_to(REPO_ROOT)} ({schema.count('CREATE TABLE ')} tables)")
    refresh_init_dump(schema)


def export_data() -> None:
    """Write a scrubbed, log-free data-only dump to backup/, then verify it."""
    BACKUP_DIR.mkdir(exist_ok=True)
    path = BACKUP_DIR / f"data-{datetime.now().astimezone():%Y-%m-%d}.sql"
    args = ["--data-only", "--no-owner", "--no-privileges"]
    args += [f"--exclude-table-data={table}" for table in EXCLUDE_DATA]
    with path.open("w") as handle:
        handle.writelines(scrub_lines(pg_dump(args)))
    size = path.stat().st_size / 1024
    print(f"wrote {path.relative_to(REPO_ROOT)} ({size:.0f} KB)")
    print(f"  emptied: {', '.join(EXCLUDE_DATA)}")
    verify(path)


def main() -> None:
    """Parse arguments and run the requested export(s)."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("what", nargs="?", default="all", choices=["all", "schema", "data"])
    what = parser.parse_args().what
    if what in ("all", "schema"):
        export_schema()
    if what in ("all", "data"):
        export_data()


if __name__ == "__main__":
    main()
